title: Shende House Canteen
theme: minimal-mistakes-jekyll

author: Ashish Shende
email: shende.ashish03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Kirti and Kiran Shende, the heart and soul behind Shende House Canteen, have dedicated the past 15 years to crafting culinary 
experiences steeped in Maharashtrian and Karnatakan traditions. 
Their passion for authentic, homemade fare shines through in every dish they serve. With unwavering commitment and a deep love for regional cuisines, Kirti and Kiran have made Shende House Canteen a cherished institution. Their culinary expertise, combined with an entrepreneurial spirit,
 brings the best of both worlds to your plate, embodying a legacy of exceptional catering and a celebration of cultural heritage."
  

# social links
twitter_username: ShendeAshish03
github_username:  shendeashish09
linkedin_username: shendeashish09

show_excerpts: true # set to false to remove excerpts on the homepage


plugins:
 - jekyll-feed
 - jekyll-seo-tag

