title: शेंडे हाऊस कॅन्टीन
theme: minimal-mistakes-jekyll

author: Ashish Shende
email: shende.ashish03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you can't explain it simply, you don't understand it well enough.
  So to learn the new technology, concepts I try to explain it through blogs.
  

# social links
twitter_username: ShendeAshish03
github_username:  shendeashish09
linkedin_username: shendeashish09

show_excerpts: true # set to false to remove excerpts on the homepage


plugins:
 - jekyll-feed
 - jekyll-seo-tag

